INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Casquinha de chocolate", 2.50, "casquinha-de-chocolate.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Casquinha de baunilha", 2.50, "casquinha-de-baunilha.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Casquinha mista", 2.50, "casquinha-mista.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Casquinha de açaí", 2.50, "casquinha-de-acai.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Casquinha de morango", 2.50, "casquinha-de-morango-editado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Casquinha de limão", 2.50, "casquinha-de-limao.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Cascão de chocolate", 3.10, "cascao-de-chocolate-editado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Cascão de baunilha", 3.10, "cascao-de-baunilha.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Cascão misto", 3.10, "cascao-misto.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Cascão de açaí", 3.10, "cascao-de-acai-editado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Cascão de morango", 3.10, "cascao-de-morango.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Cascão de limão", 3.10, "cascao-de-limao.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de abacaxi", 1.50, "picole-de-abacaxi.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de açaí", 1.50, "picole-de-acai.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de cajá", 1.50, "picole-de-caja.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de graviola", 1.50, "picole-de-graviola.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de laranja", 1.50, "picole-de-laranja.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de limão", 1.50, "picole-de-limao.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de manga", 1.50, "picole-de-manga.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de mexerica", 1.50, "picole-de-tangerina.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de morango", 1.50, "picole-de-morango.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de uva", 1.50, "picole-de-uva.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de amendoim", 1.80, "picole-leite-amendoim.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de blue ice", 1.80, "picole-leite-blue-ice.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de chocolate", 1.80, "picole-leite-chocolate.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de coco", 1.80, "picole-leite-coco-queimado.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de coco queimado", 1.80, "picole-leite-coco.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de flocos", 1.80, "picole-leite-flocos.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de l. condensado", 1.80, "picole-leite-leite-condensado.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de limão suíço", 1.80, "picole-leite-limao-suico.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. mousse maracujá", 1.80, "picole-leite-mousse-de-maracuja.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de milho verde", 1.80, "picole-leite-milho-verde.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de napolitano", 1.80, "picole-leite-napolitano.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("Picolé de romeu & julieta", 1.80, "picole-leite-romeu-e-julieta.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. ninho c/ nutella", 4.70, "paleta-de-leite-ninho-com-nutella.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. doce de leite", 4.00, "paleta-de-doce-de-leite.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. prestígio", 4.00, "paleta-de-prestigio.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. açaí c/ leite ninho", 4.70, "paleta-de-acai-com-leite-condensado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. banana c/ nutella", 4.70, "paleta-de-banana-com-nutella.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. iogurte c/ amora", 4.70, "paleta-de-iogurte-grego-com-frutas-vermelhas.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. negresco", 4.00, "paleta-de-negresco.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. l. condensado", 4.00, "paleta-de-leite-condensado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. ameixa", 4.00, "paleta-de-ameixa.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. abacaxi c/ hortelã", 4.70, "paleta-de-abacaxi.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. ovomaltine", 4.00, "paleta-de-ovomaltine.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. coco trufado", 4.70, "paleta-de-coco-trufado.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. paçoca", 4.00, "paleta-de-pacoca.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("P. m. chocolate", 4.00, "paleta-de-chocolate.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. floresta negra", 6.30, "milk-shake-de-floresta-negra.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. algodão doce", 6.30, "milk-shake-de-algodao-doce.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. Ferrero Rocher", 6.50, "milk-shake-de-ferrero-rocher.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. Ovomaltine", 6.30, "milk-shake-de-ovomaltine.jpeg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. creme", 6.30, "milk-shake-de-creme.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. uva", 6.30, "milk-shake-de-uva.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. cookie", 6.30, "milk-shake-de-cookie.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. paçoca", 6.30, "milk-shake-de-pacoca.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. pistache", 6.30, "milk-shake-de-pistache.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. chocomenta", 6.30, "milk-shake-de-chocomenta.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. menta", 6.30, "milk-shake-de-menta.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. Nutella", 6.30, "milk-shake-de-nutella.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("M.-s. blueberry", 6.30, "milk-shake-de-blueberry.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. flocos", 12.99, "sorvete-de-flocos.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. Sonho de Valsa", 12.99, "sorvete-de-sonho-de-valsa.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. Kinder Ovo", 12.99, "sorvete-de-kinder-ovo.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. coco", 12.99, "sorvete-de-coco.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. Napolitano", 12.99, "sorvete-napolitano-editado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. baunilha", 12.99, "sorvete-de-baunilha.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. tentação", 12.99, "sorvete-tentacao.jpg");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. morango", 12.99, "sorvete-de-morango-editado.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. abacaxi ao vinho", 12.99, "sorvete-de-abacaxi-ao-vinho.png");
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`, `produto`.`img`) VALUES ("S. tropical", 12.99, "sorvete-tropical-editado.png")