INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de chocolate", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de baunilha", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha mista", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de açaí", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de morango", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de limão", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de chocolate", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de baunilha", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão misto", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de açaí", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de morango", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de limão", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de abacaxi", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de açaí", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de cajá", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de graviola", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de laranja", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de limão", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de manga", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de mexerica", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de morango", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de uva", 1.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de amendoim", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de blue ice", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de chocolate", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de coco", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de coco queimado", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de flocos", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de l. condensado", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de limão suíço", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. mousse maracujá", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de milho verde", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de napolitano", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de romeu & julieta", 1.80);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. ninho c/ nutella", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. doce de leite", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. prestígio", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. açaí c/ leite ninho", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. banana c/ nutella", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. iogurte c/ amora", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. negresco", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. maracujá", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. l. condensado", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. ameixa", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. abacaxi c/ hortelã", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. ovomaltine", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. coco trufado", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. paçoca", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("P. m. chocolate", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. floresta negra", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. algodão doce", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. Ferrero Rocher", 6.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. Ovomaltine", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. creme", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. uva", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. cookie", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. paçoca", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. pistache", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. choc/enta", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. menta", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. Nutella", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("M.-s. blueberry", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. flocos", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. Sonho de Valsa", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. Kinder Ovo", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. coco", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. Napolitano", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. baunilha", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. tentação", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. morango", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. abacaxi ao vinho", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("S. tropical", 12.99);