INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de chocolate", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de baunilha", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha mista", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de açaí", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de morango", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Casquinha de limão", 2.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de chocolate", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de baunilha", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão misto", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de açaí", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de morango", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Cascão de limão", 3.10);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de abacaxi", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de açaí", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de cajá", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de graviola", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de laranja", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de limão", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de manga", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de mexerica", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de morango", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de uva", 3.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de amendoim", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de blue ice", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de chcolate", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de coco", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de coco queimado", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de flocos", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de leite condensado", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de limão suíço", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de mousse de maracujá", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de milho verde", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de napolitano", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Picolé de romeu & julieta", 3.60);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de ninho com nutella", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de morango com leite condensado", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de doce de leite", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de amora com chocolate branco", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de prestígio", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de açaí com leite ninho", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de banana com nutella", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de leite condensado com goiabada", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de chocolate branco com cereja", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de iogurte com amora", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de negresco", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de maracujá", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de leite condensado", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de ameixa", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de abacaxi com hortelã", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de ovomaltine", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de coco trufado", 4.70);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de paçoca", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Paleta mexicana de chocolate", 4.00);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de floresta negra", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de algodão doce", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de Ferrero Rocher", 6.50);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de Ovomaltine", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de creme", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de uva", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de cookie", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de paçoca", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de pistache", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de chocomenta", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de menta", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de Nutella", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Milk-shake de blueberry", 6.30);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de flocos", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de Sonho de Valsa", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de Kinder Ovo", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de coco", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de Napolitano", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de baunilha", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete tentação", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de morango", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete de abacaxi ao vinho", 12.99);
INSERT INTO `sorveteria`.`produto` (`produto`.`nome`, `produto`.`preco`) VALUES ("Sorvete tropical", 12.99);